modLoader="javafml"
loaderVersion="[54,)"
license="MIT"

[[mods]]
modId="gridless"
version="${version}"
displayName="Gridless Crafting"
description="A list-based gridless crafting and smelting overhaul for Minecraft!"
logoFile="assets/gridless/icon.png"
authors="Luigi"

[[dependencies.gridless]]
    modId="forge"
    type="required"
    mandatory=true
    versionRange="[54,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gridless]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.21.4,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="gridless-common.mixins.json"
