plugins {
    id "com.gradleup.shadow" version "9.0.0"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfig "gridless-common.mixins.json"
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

configurations.all {
    resolutionStrategy {
        force 'net.sf.jopt-simple:jopt-simple:5.0.4'
    }
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"
    annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras_version}")

    common(project(path: ":common")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive false }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set "forge"
}

jar {
    archiveClassifier.set "dev"
    destinationDirectory.set(layout.buildDirectory.dir("devlibs"))
}
